GET http://localhost:8080/movies

###

 POST http://localhost:8080/movies/add-movies
 Content-Type: application/json
 
{
           "id": "144",
            "title": "The Hateful Eight",
            "year": "2015",
            "runtime": "187",
            "genres": [
                "Crime",
                "Drama",
                "Mystery"
            ],
            "director": "Quentin Tarantino",
            "actors": "Samuel L. Jackson, Kurt Russell, Jennifer Jason Leigh, Walton Goggins",
            "plot": "In the dead of a Wyoming winter, a bounty hunter and his prisoner find shelter in a cabin currently inhabited by a collection of nefarious characters.",
            "posterUrl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjA1MTc1NTg5NV5BMl5BanBnXkFtZTgwOTM2MDEzNzE@._V1_SX300.jpg"
}

###

GET http://localhost:8080/movies/66fed5a4a23058dee96a5817

###

GET http://localhost:8080/movies?year=2007

###

GET http://localhost:8080/movies?year=2007&runtime=111

###

GET http://localhost:8080/movies?year=2007&title=Ratatouille
###

GET http://localhost:8080/movies?title=ratatoUillE
###

GET http://localhost:8080/movies?year=2007&title=rat
# Query for year: 2007
# Query for title: { '$regex': 'rat', '$options': 'i' }
# { year: 2007, title: { '$regex': 'rat', '$options': 'i' } }
###

GET http://localhost:8080/movies?genres=Animation,Comedy
# Query for genres: { '$in': [ 'Animation', 'Comedy' ] }
# { genres: { '$in': [ 'Animation', 'Comedy' ] } }

###

GET http://localhost:8080/movies?year=2007&genres=Animation,Comedy
# Query for year: 2007
# Query for genres: { '$in': [ 'Animation', 'Comedy' ] }
# { year: 2007, genres: { '$in': [ 'Animation', 'Comedy' ] } }